### ISSUE TITLE
[TO-DO] ChartJS Implementations

### ISSUE THREAD

**Issue by mneunomne** [antoniohof/edit_wars#1]
## Data Visualition

- [x] Placeholder graph with graph.js
- [x] integrate graph.js in step functions
- [x] transition between graphs
- [x] Interface elements?
- [x] Design final graphs with real date

**Comment by mneunomne** [comment]
[vue-chartjs](https://vue-chartjs.org/guide/#access-to-chart-instance)

**Comment by mneunomne** [comment]
- [ ] How to transfer the data from tableau to chart.js?

**Comment by mneunomne** [comment]
> * [ ]  How to transfer the data from tableau to chart.js?

https://www.chartjs.org/docs/latest/general/data-structures.html

**Comment by mneunomne** [comment]
## What information needs to be displayed in each chart?

### Stacked Bar Chart

- __X Axis__: Dates
- __Y Axis__: Number of headlines
- on hover: 
   - Headline text
   - origin
   - date
   - link?

**Comment by mneunomne** [comment]
[Custom Labels in Chart.js](https://github.com/antoniohof/edit_wars/issues/3)

**Comment by mneunomne** [comment]
https://threejs.org/examples/?q=sprite#webgl_points_sprites
