### ISSUE TITLE
[TO-DO] Data Navigation Tool

### ISSUE THREAD

**Issue by mneunomne** [antoniohof/edit_wars#6]
## To-do

- [ ] Define filter elements 
- [ ] Define usability buttons
- [ ] Apply filters to datavis
- [ ] Implement range slider

**Comment by mneunomne** [comment]
Range Slider Reference: https://observablehq.com/@bumbeishvili/data-driven-range-sliders
